{
	"name":"Standard",
	"inherit":[],
	"music":{},
	"sfx":{
		/*"Explosions.Long1": "wav mp3 ogg",
		"Explosions.Long2": "wav mp3 ogg",

		"Projectiles.Laser1": "wav mp3 ogg",
		"Projectiles.Laser2": "wav mp3 ogg",
		"Projectiles.Laser3": "wav mp3 ogg",
		"Projectiles.Laser4": "wav mp3 ogg",

		"Rocks.Boulder": "wav mp3 ogg",

		"Other.Powerup": "wav mp3 ogg",
		"Other.Shield": "wav mp3 ogg"*/
	},
	"images":{
		// Projectiles
		"Projectiles.Rocket": "png",
		"Projectiles.DrillRocket": "png",
		"Projectiles.FireRocket": "png",
		"Projectiles.ElectricRocket": "png",
		"Projectiles.NuclearRocket": "png",
		"Projectiles.GunShot1": "png",
		"Projectiles.GunShot2": "png",
		"Projectiles.GunShot3": "png",
		"Projectiles.BlastRangeIndicator0": "png",
		"Projectiles.BlastRangeIndicator1": "png",
		"Projectiles.BlastRangeIndicator2": "png",
		"Projectiles.BlastRangeIndicator3": "png",
		"Projectiles.BlastRangeIndicator4": "png",

		// Effects
		"Effects.Beam": "png",
		"Effects.Explosion": "png",
		"Effects.BlastWave": "png",
		"Effects.RockBlast": "png",
		"Effects.FireExplosion": "png",
		"Effects.ElectricExplosion": "png",
		"Effects.Lightning": "png",
		"Effects.NuclearExplosion": "png",
		"Effects.NuclearBlastRing": "png",
		"Effects.NuclearBlastRing2": "png",
		"Effects.NightOverlay": "png",
		"Effects.NightLight": "png",
		"Effects.LightBeam": "png",
		"Effects.FadeOut": "png",

		// Characters
		"Characters.Mayor": "png",
		"Characters.Scientist": "png",
		"Characters.ScientistHead": "png",
		"Characters.ScientistHeadSelected": "png",
		"Characters.Farmer": "png",
		"Characters.FarmerHead": "png",
		"Characters.FarmerHeadSelected": "png",
		"Characters.Woman": "png",
		"Characters.WomanHead": "png",
		"Characters.WomanHeadSelected": "png",

		// Menu and dialog stuff
		"Dialog.Button": "png",
		"Dialog.ButtonSelected": "png",
		"Dialog.ButtonDisabled": "png",
		"Dialog.ButtonShadowless": "png",
		"Dialog.ButtonShadowlessSelected": "png",
		"Dialog.HeaderBox": "png",
		"Dialog.TextBox": "png",
		"Dialog.Bubble": "png",
		"Dialog.Instructions": "png",
		"Dialog.EnhancementInstructions": "png",
		"Dialog.EditorDenial": "png",
		"Dialog.GameLogo": "png",
		"Dialog.GameLogoPipes": "png",
		"Dialog.GameComplete": "png",
		"Dialog.EditorHelp": "png",
		"Dialog.EditorSaved": "png",
		"Dialog.EditorNotEnoughRocks": "png",
		"Dialog.NextOfferArrow": "png",

		// Upgrades
		"Upgrades.btn0": "png",
		"Upgrades.btn1": "png",
		"Upgrades.btn1b": "png",
		"Upgrades.btn1c": "png",
		"Upgrades.btn2": "png",
		"Upgrades.btn2b": "png",
		"Upgrades.btn2c": "png",
		"Upgrades.btn3": "png",

		"Upgrades.Star1": "png",
		"Upgrades.Star2": "png",
		"Upgrades.Star3": "png",
		"Upgrades.RedCross": "png",

		"Upgrades.BlastRanges.l01": "png",
		"Upgrades.BlastRanges.l11": "png",
		"Upgrades.BlastRanges.l21": "png",
		"Upgrades.BlastRanges.l22": "png",
		"Upgrades.BlastRanges.l31": "png",
		"Upgrades.BlastRanges.l32": "png",
		"Upgrades.BlastRanges.l41": "png",
		"Upgrades.BlastRanges.l42": "png",

		"Upgrades.Weapons.l01": "png",
		"Upgrades.Weapons.l11": "png",
		"Upgrades.Weapons.l21": "png",
		"Upgrades.Weapons.l22": "png",
		"Upgrades.Weapons.l31": "png",
		"Upgrades.Weapons.l32": "png",
		"Upgrades.Weapons.l41": "png",
		"Upgrades.Weapons.l42": "png",

		"Upgrades.Shields.l01": "png",
		"Upgrades.Shields.l11": "png",
		"Upgrades.Shields.l21": "png",
		"Upgrades.Shields.l22": "png",
		"Upgrades.Shields.l31": "png",
		"Upgrades.Shields.l32": "png",
		"Upgrades.Shields.l41": "png",
		"Upgrades.Shields.l42": "png",

		"Upgrades.FirePower.l01": "png",
		"Upgrades.FirePower.l11": "png",
		"Upgrades.FirePower.l21": "png",
		"Upgrades.FirePower.l22": "png",
		"Upgrades.FirePower.l31": "png",
		"Upgrades.FirePower.l32": "png",
		"Upgrades.FirePower.l41": "png",
		"Upgrades.FirePower.l42": "png",

		"Upgrades.AiGunAim.l01": "png",
		"Upgrades.AiGunAim.l11": "png",
		"Upgrades.AiGunAim.l21": "png",
		"Upgrades.AiGunAim.l22": "png",
		"Upgrades.AiGunAim.l31": "png",
		"Upgrades.AiGunAim.l32": "png",
		"Upgrades.AiGunAim.l41": "png",
		"Upgrades.AiGunAim.l42": "png",

		// Building enhancements
		"BuildingEnhancements.Building1Shield1": "png",
		"BuildingEnhancements.Building2Shield1": "png",
		"BuildingEnhancements.Building3Shield1": "png",
		"BuildingEnhancements.Building4Shield1": "png",
		"BuildingEnhancements.Building5Shield1": "png",
		"BuildingEnhancements.Building6Shield1": "png",

		"BuildingEnhancements.Building1Shield2": "png",
		"BuildingEnhancements.Building2Shield2": "png",
		"BuildingEnhancements.Building3Shield2": "png",
		"BuildingEnhancements.Building4Shield2": "png",
		"BuildingEnhancements.Building5Shield2": "png",
		"BuildingEnhancements.Building6Shield2": "png",

		"BuildingEnhancements.Building1Shield3": "png",
		"BuildingEnhancements.Building2Shield3": "png",
		"BuildingEnhancements.Building3Shield3": "png",
		"BuildingEnhancements.Building4Shield3": "png",
		"BuildingEnhancements.Building5Shield3": "png",
		"BuildingEnhancements.Building6Shield3": "png",

		"BuildingEnhancements.Building1Shield4": "png",
		"BuildingEnhancements.Building2Shield4": "png",
		"BuildingEnhancements.Building3Shield4": "png",
		"BuildingEnhancements.Building4Shield4": "png",
		"BuildingEnhancements.Building5Shield4": "png",
		"BuildingEnhancements.Building6Shield4": "png",

		"BuildingEnhancements.GunStand": "png",
		"BuildingEnhancements.Gun1": "png",
		"BuildingEnhancements.Gun2": "png",
		"BuildingEnhancements.Gun3": "png",
		"BuildingEnhancements.Gun4": "png",

		// Rocks
		"Rocks.Orange1": "png",
		"Rocks.Orange1Cracks": "png",
		"Rocks.Orange2": "png",
		"Rocks.Orange2Cracks": "png",
		"Rocks.Orange3": "png",
		"Rocks.Orange3Cracks": "png",
		"Rocks.Magnetic1": "png",
		"Rocks.Magnetic1Cracks": "png",
		"Rocks.Magnetic2": "png",
		"Rocks.Magnetic2Cracks": "png",
		"Rocks.Magnetic3": "png",
		"Rocks.Magnetic3Cracks": "png",
		"Rocks.Fast1": "png",
		"Rocks.Fast1Cracks": "png",
		"Rocks.Fast2": "png",
		"Rocks.Fast2Cracks": "png",
		"Rocks.Fast3": "png",
		"Rocks.Fast3Cracks": "png",

		// Particles
		"Particles.MagneticFracture": "png",
		"Particles.OrangeFracture": "png",

		// Editor
		"Editor.SpawnArrow": "png",
		"Editor.RockButtonBackground": "png",
		"Editor.RockSelectorBox": "png",
		"Editor.EditorLine": "png",
		"Editor.Up": "png",
		"Editor.Down": "png",
		"Editor.IntervalTimer": "png",
		"Editor.Cross": "png",
		"Editor.Floppy": "png",
		"Editor.Play": "png",
		"Editor.Stop": "png",
		"Editor.Quit": "png",
		"Editor.Pause": "png",
		"Editor.NightDay": "png"
	}
}
