SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `level` (
  `lid` int(3) NOT NULL AUTO_INCREMENT,
  `levelcollection` int(3) DEFAULT NULL,
  `name` varchar(30) DEFAULT NULL,
  `createtime` timestamp NULL DEFAULT NULL,
  `savedtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `order` int(2) DEFAULT NULL,
  `hardness` float(3,2) DEFAULT NULL,
  PRIMARY KEY (`lid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=40 ;

CREATE TABLE IF NOT EXISTS `levelcollection` (
  `lcid` int(3) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) DEFAULT NULL,
  `user` int(4) DEFAULT NULL,
  PRIMARY KEY (`lcid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `levelstats` (
  `lsid` int(5) NOT NULL AUTO_INCREMENT,
  `level` int(3) DEFAULT NULL,
  `impactfactor` float(3,2) DEFAULT NULL,
  `meanfalldistance` float(4,1) DEFAULT NULL,
  PRIMARY KEY (`lsid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=557 ;

CREATE TABLE IF NOT EXISTS `rock` (
  `level` int(3) NOT NULL DEFAULT '0',
  `order` int(3) NOT NULL DEFAULT '0',
  `type` varchar(20) DEFAULT NULL,
  `rocklevel` int(1) DEFAULT NULL,
  `spawndelay` int(3) DEFAULT NULL,
  `x` int(3) DEFAULT NULL,
  `dir` float(4,3) DEFAULT NULL,
  PRIMARY KEY (`level`,`order`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
